### ISSUE TITLE
Typing in whiteboard still activates specific keybinds

### ISSUE THREAD

**Issue by Koishukaze** [ZehsTeam/Lethal-Company-Whiteboard#1]
Typing any text in the text input activates the specific keybind, in my case (for the video shown below);
F = Flashlight
C = Emote wheel
f11 = Die

https://github.com/user-attachments/assets/84700731-a607-4146-9515-597c8f91428b

**Comment by ZehsTeam** [comment]
@Koishukaze These are all modded hotkeys so I don't think there is really anything I could do.

**Comment by Koishukaze** [comment]
> @Koishukaze These are all modded hotkeys so I don't think there is really anything I could do.

Indeed so I’m unsure on how to solve the issue, just thought I’d mention it if you had some idea, perhaps there’s a way to block all hotkeys while still registering the keypress? I’m insure

**Comment by ZehsTeam** [comment]
@Koishukaze Good news! Everything is fixed in the latest update.
